defmodule ElixirTorrentWebUIWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :elixir_torrent_web_ui

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_elixir_torrent_web_ui_key",
    signing_salt: "Msu+Jejo",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :elixir_torrent_web_ui,
    gzip: not code_reloading?,
    only: ElixirTorrentWebUIWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  # The macOS launcher polls `GET /api/torrents` every two seconds to keep the
  # Dock menu current. At the default `:info` that is two lines per poll —
  # tens of megabytes of chatter in the packaged app's `server.log`. Routine
  # polls log at `:debug`; every other request keeps `:info`.
  plug Plug.Telemetry,
    event_prefix: [:phoenix, :endpoint],
    log: {__MODULE__, :request_log_level, []}

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ElixirTorrentWebUIWeb.Router

  @doc """
  Per-request log level for `Plug.Telemetry`.

  Only the launcher's Dock poll is demoted — `POST /api/torrents` adds a
  torrent and stays at `:info`, as does everything else.
  """
  @spec request_log_level(Plug.Conn.t()) :: Logger.level()
  def request_log_level(%Plug.Conn{method: "GET", path_info: ["api", "torrents"]}), do: :debug
  def request_log_level(%Plug.Conn{}), do: :info
end
