import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :elixir_torrent_web_ui, ElixirTorrentWebUIWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force SSL for server deployments. Skipped for the local desktop .app bundle
# (see ELIXIR_TORRENT_DESKTOP_BUILD when running `mix mac.dmg`).
unless System.get_env("ELIXIR_TORRENT_DESKTOP_BUILD") == "1" do
  config :elixir_torrent_web_ui, ElixirTorrentWebUIWeb.Endpoint,
    force_ssl: [rewrite_on: [:x_forwarded_proto]],
    exclude: [
      hosts: ["localhost", "127.0.0.1"]
    ]
end

# Do not print debug messages in production
config :logger,
  level: :info,
  compile_time_purge_matching: [
    [level_lower_than: :info]
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
